# Colors
BACKGROUND_COLOR = (192, 192, 192)
CELL_COLOR = (128, 128, 128)

# Sizes
BOARD_SIZE = (10, 10)
CELL_SIZE = (32, 32)
HORIZONTAL_BORDER_SIZE = (16, 16)
VERTICAL_BORDER_SIZE = (100, 16)
DISPLAY_SIZE = (BOARD_SIZE[0] * CELL_SIZE[0] + HORIZONTAL_BORDER_SIZE[0] + HORIZONTAL_BORDER_SIZE[1],
                BOARD_SIZE[1] * CELL_SIZE[1] + VERTICAL_BORDER_SIZE[0] + VERTICAL_BORDER_SIZE[1])

# Others
BASE_IMAGES_PATH = "images"
NUM_OF_MINES = 9
NUM_OF_RIGHT_NEIGHBORS = 4
NUM_OF_LEFT_NEIGHBORS = 4
