TOP_BORDER_HEIGHT = 100
BOTTOM_BORDER_HEIGHT = 16

LEFT_BORDER_WIDTH = 16
RIGHT_BORDER_WIDTH = 16

ROWS = 10
COLS = 10

GRID_WIDTH = 32
GRID_HEIGHT = 32

TOTAL_HEIGHT = TOP_BORDER_HEIGHT + BOTTOM_BORDER_HEIGHT + ROWS * GRID_HEIGHT
TOTAL_WIDTH = LEFT_BORDER_WIDTH + RIGHT_BORDER_WIDTH + COLS * GRID_WIDTH

SIDE_BORDERS_HEIGHT = TOTAL_HEIGHT - TOP_BORDER_HEIGHT - BOTTOM_BORDER_HEIGHT

TABLE_WIDTH = TOTAL_WIDTH - LEFT_BORDER_WIDTH - RIGHT_BORDER_WIDTH
TABLE_HEIGHT = TOTAL_HEIGHT - TOP_BORDER_HEIGHT - BOTTOM_BORDER_HEIGHT
